### ISSUE TITLE
HTTP Return Codes

### ISSUE THREAD

**Issue by qvalentin** [open-schnick/NotEnoughWood#14]
If a log is not found it should return 404.

**Comment by open-schnick** [comment]
where does this happen to you? When a log file doesn't exist the server returns 404.
![Screenshot from 2021-04-12 09-31-59](https://user-images.githubusercontent.com/60597856/114357416-00fba180-9b72-11eb-974c-8b138f4fc44f.png)

**Comment by qvalentin** [comment]
I was missing the -f flag when using curl. With this the pipeline should fail when the log is not found.
