### ISSUE TITLE
[FEATURE] - Make header optional depending on request

### ISSUE THREAD

**Issue by qvalentin** [open-schnick/NotEnoughWood#4]
If I want to use NEW to automate stuff it would be nice to have an option to disable the custom header and just send the logs as plain text.

**Comment by qvalentin** [comment]
Maybe it should show the header, but sending the response as plain text and not as html would be much nicer if you use the tool from the cli with curl.

**Comment by open-schnick** [comment]
how would you implement that? By checking the user agent of the request?

**Comment by qvalentin** [comment]
User agent checking could be complicated. Maybe you can check for an origin header or something else, that is only set by browsers.

**Comment by open-schnick** [comment]
@qvalentin i implemented this in v.1.1.2
